### PR TITLE
Integrating Esperanto tranlsations

### PR DESCRIPTION
**Pull request by psychoslave**
Please review this commits especially if you speak Esperanto.

### CODE REVIEW

**Comment by my2iu** [comment]
Great. Thanks a lot. I'll try to take a look at this some time over the next couple of days.

**Comment by my2iu** [comment]
Is it possible to also put the keyword translation also under the terms of CC0, like the translation of the objects and methods? Then if other people make programming languages, they can easily add Esperanto support. 

In any case, CC-BY-SA won't work because it's not clear how that applies to a programming language. Does all code that uses the Esperanto version of Babylscript need to include an attribution? How about programs that contain Esperanto code? How does the attribution work? etc. etc.

**Comment by psychoslave** [comment]
No problem for the keywords. I also added many comments explaining lexical choices in the google documents. I don't know the originals license, I guess it's gpl/mpl. 

I'm interested with share alike constraints but I don't really care of attribution. Now easying works of anyone who would like to create Esperanto programming language is more important, so cc0 is fine. for a simple list of corresponding words, I doubt that anyone can claim copyright anyway.

-----Message d'origine-----
De : Ming Iu notifications@github.com
À : my2iu/babylscript babylscript@noreply.github.com
Cc : psychoslave psychoslave@culture-libre.org
Envoyé : vendredi 19 févr. 2016 04:24:48 UTC+00:00
Objet : Re: [babylscript] Integrating Esperanto tranlsations (#2)

Is it possible to also put the keyword translation also under the terms of CC0, like the translation of the objects and methods? Then if other people make programming languages, they can easily add Esperanto support. 

In any case, CC-BY-SA won't work because it's not clear how that applies to a programming language. Does all code that uses the Esperanto version of Babylscript need to include an attribution? How about programs that contain Esperanto code? How does the attribution work? etc. etc.

---

**Comment by my2iu** [comment]
Ok, I've merged your changes in. I adjusted the license on the keyword translation to match our discussion. Apparently, I forgot how Babylscript worked, and I ended up having to make some fixes to get everything merged in. I created a small unit test, and it seemed to work fine running the following code:

```
---eo---
variabla a = 2; 
se (vera) 
   a += 3; 
alie 
   a += 1; 
a;
```

I'll try to generate a new binary version of the code for the website when I get a chance.

Thanks a lot for creating an Esperanto translation!

**Comment by my2iu** [comment]
Oh, one thing I'm not sure about is that you don't use any capital letters. I don't think it's a problem here, but it could potentially cause problems with other languages like Java where the `boolean` keyword and `Boolean` class are different things. I think the only place where this occurs in JavaScript is with `function` and `Function` but you translated them differently, so I guess it's ok.

**Comment by psychoslave** [comment]
Great, I wasn't able to do it alone. I'll try with your merged version 
as soon as I can. I'm so happy to have a first Esperanto programming 
language. Actually my goal is to have more specific languages which 
fully benefits from Esperanto's regurlar syntax.

But translating existing languages is already a good milestone. And 
babylscript was a great way to ease this first step, thank you. :)

**Comment by psychoslave** [comment]
Well, that's because, as said in the previous email, I already have in 
mind how I would like to use linguistic characteristics of Esperanto to 
manage this distinction in a more idiomatic way.

Esperanto is an agglutinative language which tends to create fully 
explicit words on the fly. So one may use
- "buleklaso" - that is "bule-klaso" which may translate as "boolean
  class" - instead  of "Boolean"
- "bulea" or even "buleeca" for the primitive type. Indeed -ec- is an
  affix which stands for "which have the property/quality of". Also
  words which end with "-a" are adjectives. And you form other
  grammatical types by substituting this termination. For example all
  words which end up with "-o" are substantives, that is "name", which
  is perfect for a variable, type and classes names for example.

That's why I translated "Function" as funkcio, that is "the object that 
matches the description of the root 'funkc-'", while I translated 
"function" as "funkcia", that is "make the following object have the 
quality of the root 'funkc-'". Well, admittedly funkcklaso would be more 
accurate, but should be generally explicit enough.  I didn't defined an 
accurate rule, for example I used "signtipa" to translate "char", when 
"signa" would - I guess - be just as fine.

Also note that I didn't made literal translation, like "bulea" at all. 
Indeed I also try to make the whole resulting translation more accurate, 
generic and coherent. So while "boolean" is translatable as "bulea", it 
doesn't accurately describe what it is referring to, as it's an 
antonomastic term. That's why I opted for "duvalenta" as translation, 
that may be translated as "bivalent" in English. Note that it's not just 
more accurate regarding the thing it's talking about, it's also more 
generic as one may easily extends the name : "unuvalenta", "trivalenta", 
that is "monovalent", "trivalent" and so on.

**Comment by psychoslave** [comment]
Hi,

I merged back your changes in my own repository. In the process I turned 
back unicode characters to their unescaped version within commentaries.  
Hopefully it won't create problem. Now, I don't know what I did wrong, 
but I can't run even the sample.js program anymore :

# LANG=C java -jar build/babylscriptrun.jar babylrunner/sample.js

Exception in thread "main" org.mozilla.javascript.EvaluatorException: 
missing ; before statement
     at 
org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
     at 
org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:96)
     at 
org.mozilla.javascript.ParserErrorReportingBase.addError(ParserErrorReportingBase.java:40)
     at 
org.mozilla.javascript.ParserErrorReportingBase.reportError(ParserErrorReportingBase.java:52)
     at org.mozilla.javascript.Parser.statementHelper(Parser.java:1232)
     at org.mozilla.javascript.Parser.statement(Parser.java:672)
     at org.mozilla.javascript.Parser.parse(Parser.java:364)
     at org.mozilla.javascript.Parser.parse(Parser.java:300)
     at org.mozilla.javascript.Context.compileImpl(Context.java:2451)
     at org.mozilla.javascript.Context.compileString(Context.java:1367)
     at org.mozilla.javascript.Context.compileString(Context.java:1356)
     at org.mozilla.javascript.Context.evaluateString(Context.java:1109)
     at Runner.<init>(Runner.java:23)
     at Runner.main(Runner.java:73)

Is it a problem within the java code or the javascript one ? I guess it 
would be the former one since I didn't touch the javascript.

**Comment by my2iu** [comment]
It's a problem with the Java code. Somehow the compiler is broken to the point that it has a syntax error as soon as it tries to run any JavaScript.

Did you carefully merge in my changes? There were a few bugs in your code that I also fixed up. Notably, the English version of JavaScript was accidentally broken in your version.

For .properties files, many versions of Java expect them to be in 8859-1. It turns out that I modified the Babylscript compiler previously not to read them on startup (they are preprocessed in a separate stage). So you won't encounter any errors, but the files are invalid in UTF-8 form and can't be used by the preprocessor.

**Comment by psychoslave** [comment]
Le 21/02/2016 20:52, Ming Iu a écrit :

> It's a problem with the Java code. Somehow the compiler is broken to 
> the point that it has a syntax error as soon as it tries to run any 
> JavaScript.
> 
> Did you carefully merge in my changes? There were a few bugs in your 
> code that I also fixed up. Notably, the English version of JavaScript 
> was accidentally broken in your version.

Well, I did, but it looks like it wasn't carefully enough. ^^

> For .properties files, many versions of Java expect them to be in 
> 8859-1. It turns out that I modified the Babylscript compiler 
> previously not to read them on startup (they are preprocessed in a 
> separate stage). So you won't encounter any errors, but the files are 
> invalid in UTF-8 form and can't be used by the preprocessor.
> 
> Couldn't the preprocessor make the UTF-8 to 8859-1 conversion ? That 
> would avoid having working files with \uxxxx signs.

I will try to sanitize my own repository with a propper merging. I 
already tested a now code with your merge commit, and it looks like it 
works fine. See the specimeno.js attached

**Comment by my2iu** [comment]
It's good to hear that it's working for you.

The .properties file format says that they should be in 8859-1 format. Normally, they aren't edited by hand but in a .properties file editor that handles the \uxxxx conversions for you. If you want to check in a file in UTF-8 format that's human-readable, you should check that in as a different file and have a converter convert that file into a .properties file.

**Comment by psychoslave** [comment]
Hi Ming,

Sorry I wasn't very active lately on this project, I'm currently rather 
busy on other topics, but I will come back with more contributions soon.

**Comment by my2iu** [comment]
Sorry too. I've been busy as well. I only now found the time to update the Babylscript website with your translation.

**Comment by psychoslave** [comment]
great news thank you

**Pull request closed without merging**
